name: Build and Test

on:
  push:
    paths: 
      - 'main.py'                                                                                  

jobs:      
  build_and_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run Program
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt   
        python3 main.py
